### ISSUE TITLE
question in the roslaunch contact_stability pedular.launch

### ISSUE THREAD

**Issue by junhyeokahn** [stephane-caron/contact_stability#1]
Hi,
First of all I really appreciate you to open this nice studies to  the world.
I am trying to run your code in Ubuntu 14.04 ros jade.
After I set up dependencies, when I type roslaunch contact_stability pedular.launch
it returns,
in pendular_server.py, 40 line, no module named SupportArea

I also tried to check rossrv show command, and there were only pendular area and static area

**Comment by stephane-caron** [comment]
Hi,

After you run ``catkin_make``, the ``SupportArea`` service should be build into your catkin workspace (in the folder ``/path/to/your/catkin_ws/devel/lib/python2.7/dist-packages/contact_stability``). Can you check that:
- You ran ``catkin_make`` in your catkin WS
- You sourced the setup script in your workspace, e.g. if your shell is bash by running
```bash
source /path/to/your/catkin_ws/devel/setup.bash
```
After these two steps the import should work.

**Comment by junhyeokahn** [comment]
Thank you for reply,
I just catkin_make and check the directory in devel.
There are only init.py/c, pendulararea.py/c, staticarea.py/c

**Comment by stephane-caron** [comment]
OK, that's not how it should be (the files ``__init__.py``, ``pendular.py`` and ``static.py`` should be in ``/your/catkin_ws/src/contact_stability/src/contact_stability``, yes, the last two folders are repeated). Are you sure that ``/your/catkin_ws/src/contact_stability`` is the full git repository, i.e. contains ``CMakeLists.txt``, the ``msg/`` and ``srv/`` folders, etc.?

I guess something is broken in your install. If it still doesn't work, you can provide some more info:
- List the files in ``/your/catkin_ws/src/contact_stability/`` and paste the output here.
- Remove the build/ and devel/ folders in your catkin_ws, do a ``catkin_make`` again and paste the output here.
- List the files in ``/your/catkin_ws/devel/lib/python2.7/dist-packages/contact_stability`` and paste the output here.

**Comment by junhyeokahn** [comment]
In my contact_staility,
```
junhyeok@junhyeok-MacBookPro:~/catkin_ws/src/contact_stability$ ls 
CMakeLists.txt  LICENSE  package.xml  README.md  setup.py  srv
launch          msg      pymanoid     scripts    src       test
```
After remove and re-catkin_make and log file
```
junhyeok@junhyeok-MacBookPro:~/catkin_ws$ catkin_make
Base path: /home/junhyeok/catkin_ws
Source space: /home/junhyeok/catkin_ws/src
Build space: /home/junhyeok/catkin_ws/build
Devel space: /home/junhyeok/catkin_ws/devel
Install space: /home/junhyeok/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/junhyeok/catkin_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/junhyeok/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/junhyeok/catkin_ws/devel;/opt/ros/jade
-- This workspace overlays: /home/junhyeok/catkin_ws/devel;/opt/ros/jade
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/junhyeok/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - contact_stability
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'contact_stability'
-- ==> add_subdirectory(contact_stability)
-- Using these message generators: gencpp;geneus;genlisp;genpy
-- contact_stability: 1 messages, 2 services
-- Configuring done
-- Generating done
-- Build files have been written to: /home/junhyeok/catkin_ws/build
####
#### Running command: "make -j8 -l8" in "/home/junhyeok/catkin_ws/build"
####
[  0%] [  0%] Built target std_msgs_generate_messages_py
Built target geometry_msgs_generate_messages_py
[  0%] [  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
Built target geometry_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target _contact_stability_generate_messages_check_deps_PendularArea
[  0%] Built target _contact_stability_generate_messages_check_deps_Contact
[  0%] Built target _contact_stability_generate_messages_check_deps_StaticArea
[ 13%] [ 13%] [ 20%] [ 26%] [ 33%] [ 40%] Generating Python from MSG contact_stability/Contact
Generating EusLisp code from contact_stability/Contact.msg
[ 46%] [ 53%] Generating EusLisp code from contact_stability/StaticArea.srv
Generating Lisp code from contact_stability/Contact.msg
Generating EusLisp code from contact_stability/PendularArea.srv
Generating C++ code from contact_stability/Contact.msg
Generating Lisp code from contact_stability/StaticArea.srv
Generating Python code from SRV contact_stability/StaticArea
[ 60%] [ 66%] Generating Python code from SRV contact_stability/PendularArea
[ 73%] Generating C++ code from contact_stability/StaticArea.srv
[ 80%] Generating Lisp code from contact_stability/PendularArea.srv
[ 86%] Generating EusLisp manifest code for contact_stability
Generating C++ code from contact_stability/PendularArea.srv
[100%] [100%] [100%] Built target contact_stability_generate_messages_lisp
Generating Python srv __init__.py for contact_stability
Generating Python msg __init__.py for contact_stability
[100%] Built target contact_stability_generate_messages_py
[100%] Built target contact_stability_generate_messages_cpp
[100%] Built target contact_stability_generate_messages_eus
[100%] Built target contact_stability_generate_messages
```
After re-catkin make in my contact_stability dircetory,
```
junhyeok@junhyeok-MacBookPro:~/catkin_ws/src/contact_stability$ ls
CMakeLists.txt  launch  LICENSE  msg  package.xml  pymanoid  README.md  scripts  setup.py  src  srv  test
```
In my dist-packages/contact_stability,
```
junhyeok@junhyeok-MacBookPro:~/catkin_ws/devel/lib/python2.7/dist-packages/contact_stability$ ls
__init__.py  msg  srv
```
in srv
```
junhyeok@junhyeok-MacBookPro:~/catkin_ws/devel/lib/python2.7/dist-packages/contact_stability/srv$ ls
__init__.py  _PendularArea.py  _StaticArea.py
```

**Comment by stephane-caron** [comment]
Okay, all of this looks correct!

Next question: if you run
```bash
$ cd ~/catkin_ws/devel/lib/python2.7/dist-packages/
$ python -c "import contact_stability.srv"
```
Does it work, or does it print an ImportError to the terminal?

**Comment by junhyeokahn** [comment]
it works well in dist-packages directory,
but still not work for roslaunch

**Comment by stephane-caron** [comment]
This means that you have not sourced the ``setup.bash`` script correctly. As I was writing above, you need to add the line
```bash
source /path/to/your/catkin_ws/devel/setup.bash
```
to your ``~/.bashrc`` file (if you use Bash--for Zsh it will be ``setup.zsh`` and ``~/.zshrc``). Then exit the terminal and start it again for the change to take effect.

You can check if the file has been sourced correctly by typing:
```bash
$ echo $CATKIN_SHELL
```
It should write the name of your shell. You can also do
```bash
$ echo $PYTHONPATH
```
and check that the resulting string contains "catkin_ws/devel/lib/python2.7/dist-packages".

**Comment by junhyeokahn** [comment]
I make sure I sourced it but still says cannot import name SupportArea from srv
```bash
junhyeok@junhyeok-MacBookPro:~/catkin_ws$ echo $CATKIN_SHELL 
bash
junhyeok@junhyeok-MacBookPro:~/catkin_ws$ echo $PYTHONPATH 
/home/junhyeok/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/jade/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages
```

**Comment by stephane-caron** [comment]
OK, sorry that was my mistake. I just pushed a fix: can you ``git pull``, do a ``catkin_make`` and try again?

**Comment by junhyeokahn** [comment]
Thanks for your answer,
I think now I have different import error
```
Traceback (most recent call last):
  File "/home/junhyeok/catkin_ws/src/contact_stability/scripts/static_server.py", line 43, in <module>
    from pymanoid import register_env, ContactSet, Contact
ImportError: No module named pymanoid
Traceback (most recent call last):
  File "/home/junhyeok/catkin_ws/src/contact_stability/scripts/pendular_server.py", line 42, in <module>
    from pymanoid import register_env, Contact, ContactSet
ImportError: No module named pymanoid
```

**Comment by stephane-caron** [comment]
Okay for this one you most likely forgot to clone with the ``--recursive`` option. If that's the case your directory ~/catkin_ws/src/contact_stability/pymanoid/ will be empty.

Just go to the ~/catkin_ws/src/contact_stability/ repository and do:
```bash
$ git submodule init
$ git submodule update
```
After this, the pymanoid/ directory should contain the missing module.

**Comment by junhyeokahn** [comment]
It says I don't have correct access for it, can I just git pull your pymanoid repository(which is same head)

**Comment by junhyeokahn** [comment]
for that I just re clone it with recursive,
However, now it says 
```
Traceback (most recent call last):
  File "/home/junhyeok/catkin_ws/src/contact_stability/scripts/static_server.py", line 105, in <module>
    pool = pebble.process.Pool(NB_WORKERS)
AttributeError: 'module' object has no attribute 'process'
Traceback (most recent call last):
  File "/home/junhyeok/catkin_ws/src/contact_stability/scripts/pendular_server.py", line 107, in <module>
    pool = pebble.process.Pool(workers=NB_WORKERS, )
AttributeError: 'module' object has no attribute 'process'
```
One thing I need to mention is I installed pebble so when I run 
```
python
>>> import pebble
```
there was no error

**Comment by stephane-caron** [comment]
I just pushed an update, now you should be able to access it (after you ``git pull``).

Alternatively, yes, it's OK if you just git clone [pymanoid](https://github.com/stephane-caron/pymanoid.git) and replace the empty pymanoid/ folder with it.

**Comment by stephane-caron** [comment]
For Pebble, make sure you have the correct version of the library installed on your system with:
```bash
$ sudo pip install Pebble==3.1.14
```

**Comment by junhyeokahn** [comment]
I am so sorry for this kind of easy questions, don't have many experience in python
```sudo pip install Pebble==3.1.14``` generate a directory in my dist-packages
I guess I need to do more process in here.
What would I do?

**Comment by stephane-caron** [comment]
No problem.

Normally, ``pip install`` should create a new directory ``/usr/local/lib/python2.7/dist-packages/pebble`` that installs pebble for your whole system. Then, you can try running the roslaunch again and it should find the 'process' attribute in the 'pebble' module (which was previously missing).

If it still doesn't work, it may be because you have your previous installation of Pebble taking precedence over the new one. Try uninstalling that previous version and then do the pip install again.

**Comment by junhyeokahn** [comment]
Ah now I have no compiling error! Thank you so much.
Also could you tell me which head(version) of 'fcl' and 'openrave' are you using?
fcl recently changed its directory structure so I just pulled 2015 Oct.
I think I have the problem of openrave side
```
2017-02-22 14:53:53,355 openrave [WARN] [plugindatabase.h:577 InterfaceBasePtr OpenRAVE::RaveDatabase::Create] Failed to create name fcl_, interface collisionchecker
2017-02-22 14:53:53,379 openrave [WARN] [plugindatabase.h:577 InterfaceBasePtr OpenRAVE::RaveDatabase::Create] Failed to create name fcl_, interface collisionchecker
```

**Comment by stephane-caron** [comment]
Thanks for your feedback :) I'm glad it worked out.

The FCL warning you get is [quite common](https://github.com/rdiankov/openrave/issues/397). I wrote some install instructions [here](https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html) (you will find the versions of openrave and fcl I use there), but you should not worry about this warning: on the machine I'm currently working on, I have it every time I run openrave and it does no harm.

All the best!

**Comment by junhyeokahn** [comment]
As a  beginner in robotics area, it was a great honor to learn from you. Thanks!
